### ISSUE TITLE
Wallet management 

### ISSUE THREAD

**Issue by ismaeljoseph** [GoteoFoundation/goteo#102]
good morning everyone,
I install a goteo installation and I have a group of people who want to support a musical project, how can I have these features with Goteo:
1- the entire fund of a contributor is on his wallet 
2- each wallet is divided into two (sub wallets). sub wallet 1 amount available for musical project and sub wallet 2 amount for another project
3- The amount of sub wallet 1 of each contributor will be added to a global fund for a musical project. information about the global fund will be public for anyone who want to submit a musical  project.
The global fund could be associate to a regular projet ( for exemple: funding fund for music projects) on goteo with no end date. 
4- wallet 2 will be used as the regular wallet on goteo.
5- I also want to have the amount in Haitian currency.

I'm trying  to fight to convince my people to work together. Please help.

**Comment by microstudi** [comment]
Hi, Currently there's only one (virtual) wallet to use in goteo.
Wallets needs to be recharged by the user and, then, they can spend it on the projects they want.
I'm not sure what's your problem here, if you want a very specific behaviour of the money flow you are going to need to dive into the plugin system (and create a new one). 
But we cannot give you assistance for specific developings, we can only help you if you have code in place and tell you if you're right or wrong.
