### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined method Goteo\Model\Banner::getSection()

### ISSUE THREAD

**Issue by ramoncodit** [GoteoFoundation/goteo#107]
Hi all,
after installed the project with dockers option (goteo-php, goteo-mariadb and goteo-webserver)
I had logged in as a 'admin' and I tried to create a new Banner from scratch, in menu option:
- /admin/banners

with 'New Banner' button. Without selecting any project, I can attach an image and create banner.
Then, when I go to front, I get this error:

`( ! ) Fatal error: Uncaught Error: Call to undefined method Goteo\Model\Banner::getSection() in /application/Resources/templates/responsive/partials/components/main_slider.php on line 36`

After that, I went to /project/create, I created a new project (all  steps) and then I returned to /admin/banners, I updated 'project' info for that banner, but the error still appears in front.

In other hand, I searched the line error but I didn't found any getSection method in Goteo/Model/Banner.php, as it is called in main_slider.php ...

What are the correct steps or where can I find some docs please?
Thanks in advance
Greetings

**Comment by microstudi** [comment]
Thanks for reporting, this is clearly a mistake on our part, because we're mixing 2 different models in that view (the `getSection()` function comes from the Post model).
We will look into it, but for the moment, you should get rid of that by ensuring that all your banners have always the `title` and `description` fields fulfilled.

I'll leave the issue opened and we will close it when fixed. thanks

**Comment by davidbeig** [comment]
This issue is fixed in this [commit](https://github.com/GoteoFoundation/goteo/commit/bfc079a1587c77573382966ba6ab05775746e457). Closing.
