### ISSUE TITLE
Cannot find node management for users

### ISSUE THREAD

**Issue by alexm** [GoteoFoundation/goteo#130]
I'm upgrading from v3.2.1 and I can't find how to move a user to another node in the admin menus anymore. Moreover, when accessing directly the route `/admin/users/move/foobar` now I get this error (it works fine on v3.2.1):

```
Symfony\Component\HttpKernel\Exception\NotFoundHttpException: Route [/move/foobar] is not defined in module [Goteo\Controller\Admin\UsersAdminController]
 at Goteo.Controller.AdminController.routingAction(AdminController.php:132)
 at Symfony.Component.HttpKernel.HttpKernel.handleRaw(HttpKernel.php:135)
 at Symfony.Component.HttpKernel.HttpKernel.handle(HttpKernel.php:57)
 at Goteo.Application.App.run(App.php:178)
 at (main)(index.php:49)
```

**Comment by davidbeig** [comment]
Hi Alex!

In the [RELEASE_NOTES.md](https://github.com/GoteoFoundation/goteo/blob/devel/RELEASE_NOTES.md) you can see that in the release 3.4 we added the new admin framework.

I guess that you are updating from 3.2.1 to >= 3.4.

You can find the new admin for users in UsersAdminController where you'll find that the route you try to access is not defined, but it's still in the old controller -> UsersSubController.php:moveAction().

In order to have again that functionality you can add it to the new UsersAdminController and add all the necessary to the new view that is in /Resources/templates/responsive/admin/users/...

I hope this helps you!

**Comment by alexm** [comment]
Hi David :smile: 

> In the [RELEASE_NOTES.md](https://github.com/GoteoFoundation/goteo/blob/devel/RELEASE_NOTES.md) you can see that in the release 3.4 we added the new admin framework.

Sure, I'm aware of that. However, I'm wondering whether the missing features that were available before are being discarded or they'll eventually be added back. Adding this kind of information on the release notes would be very helpful to keep my fork as close as possible to yours.

> I guess that you are updating from 3.2.1 to >= 3.4.

Yes, from v3.2.1 to v3.5.1.

> You can find the new admin for users in UsersAdminController where you'll find that the route you try to access is not defined, but it's still in the old controller -> UsersSubController.php:moveAction().
> 
> In order to have again that functionality you can add it to the new UsersAdminController and add all the necessary to the new view that is in /Resources/templates/responsive/admin/users/...

I could do that but if this feature is discarded forever, maybe I'll just make all users members of all nodes by default so I don't need to worry anymore.

Thanks!

**Comment by davidbeig** [comment]
> I'm wondering whether the missing features that were available before are being discarded or they'll eventually be added back. Adding this kind of information on the release notes would be very helpful to keep my fork as close as possible to yours.

They are not of any use right now for how we are using the platform. But we still have to discuss wether we want those functionalities back or not.

> I could do that but if this feature is discarded forever, maybe I'll just make all users members of all nodes by default so I don't need to worry anymore.

I think that it would be better if you do that, since it might take a while before we add that back to this repo in the new admin modules. 

Hope I answered everything you needed!

**Comment by alexm** [comment]
Thank you! This is all I needed to know.
