### ISSUE TITLE
Rewards set to 0

### ISSUE THREAD

**Issue by getsei** [GoteoFoundation/goteo#145]
Hello Team,

The following setting is in defaults.yml file. I changed the value to 0 but still a new project requires 3 rewards. 

# Default required rewards
rewards:
    required: 3

Is rewards a mandatory functionality in the system? Otherwise what's the easiest way to disable it?

Thanks

**Comment by microstudi** [comment]
The easiest way would be to change this line, remove the `abs` function and put your value to -1 :

https://github.com/GoteoFoundation/goteo/blob/f90492f1478553f3ae84edf2fe035f96870e438f/src/Goteo/Application/Event/ProjectValidationEvent.php#L230

You could PR this change if you want. Otherwise you will have to make this change everytime you update the code

A more advance way to do it would be by creating a custom plugin and register a new listener for the AppEvents::PROJECT_VALIDATION with a custom logic.

**Comment by getsei** [comment]
Thanks microstudi, that's well explained.
