### ISSUE TITLE
Not sending Emails.

### ISSUE THREAD

**Issue by dessHub** [GoteoFoundation/goteo#32]
Hello!

I have set the "env : real" , but i get internal server error. 
Here are my variables settings:

`    transport:
        from:          my-email@gmail.com,
        name:          Goteo Sender,
        type:          smtp,
        # if type is smtp:
        smtp:
            auth:     true,
            secure:   ssl,
            host:     smt.gmail.com,
            port:     587,
            username: myemail@gmail.com,
            password: my-email-password
`

**Comment by microstudi** [comment]
smt.gmail.com sound like it should be smtp.gmail.com ?

**Comment by dessHub** [comment]
@microstudi I have updated it but still getting the same error.

**Comment by microstudi** [comment]
If your using gmail you should make sure that you can actually send using smtp. It may not be active by default.
Also it would be nice to get the full error message, otherwise is hard to know where is the real problem.
settings.yml should be a valid YAML format, I supose you're posting all the variables in the same line for brevity but I'd prefer to view exactly as you have in your settings.yml (removing password of course)

**Comment by dessHub** [comment]
Here is what i have:
`transport:`
       `from:          desshub95@gmail.com`
        `name:          desmond korir`
         `type:          smtp`

         `# if type is smtp:`       
          `smtp:`
                 `auth:     true`
                 `secure:   ssl`
                 `host:     smtp.gmail.com`
                 `port:     587`
                 `username: desshub95@gmail.com`
                 `password: password`
