### ISSUE TITLE
Bitpay Payment Gateway Integration

### ISSUE THREAD

**Issue by marshadshaheen** [GoteoFoundation/goteo#88]
Hi
anyone who could help to add another gateway "Omnipay\Bitpay"
I want to relevant files to be updated/created
thanks

**Comment by microstudi** [comment]
Are you willing to implement it and need some help? or are you asking for anyone else to do it?

**Comment by marshadshaheen** [comment]
I want to implement it myself and contribute to this opensource

**Comment by microstudi** [comment]
Payment methods must be added in specific classes. For example:
`Goteo/Payment/Method/PaypalPaymentMethod.php`
Then the method must be added (via plugin or in Config.php:
`\Goteo\Payment\Payment::addMethod('Goteo\Payment\Method\PaypalPaymentMethod');`

This class uses an Omnipay module that should be added through composer.

But you will need to dive a little bit and experiment in order to get the things done.

**Comment by davidbeig** [comment]
Closing this issue because there was no response.
